name: uia
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core_platform_interface: 4.5.1
  flutter_svg: ^1.0.3
  animations: ^2.0.2
  cloud_firestore: ^3.3.0
  font_awesome_flutter: ^10.1.0
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^3.3.18
  get: ^4.6.3
  shared_preferences: ^2.0.15
  google_sign_in: ^5.3.1
  google_fonts: ^3.0.1
  future_progress_dialog: ^0.2.0
  lottie: ^1.3.0
  flutter_custom_tabs: ^1.0.4
  emojis: ^0.9.9
  assets_audio_player: ^3.0.4+3
  fluttertoast: ^8.0.9

  dotted_border: ^2.0.0+2
  social_share: ^2.2.1
  logger: ^1.1.0
  stacked: ^2.2.7+1
  stacked_services: ^0.8.16
  streaming_shared_preferences: ^2.0.0
  flutter_native_splash: ^2.1.6
  enum_to_string: ^2.0.1
  firebase_core: 1.21.0
  webview_flutter: ^3.0.4
  flutter_pollfish: ^4.0.7
  url_launcher: ^6.1.3
  firebase_messaging: ^11.2.11
  timeago: ^3.2.2
  overlay_support: ^1.2.1
  flutter_polygon: ^0.2.0
  cloud_functions: ^3.3.3
  firebase_auth_platform_interface: ^6.5.4
  cloud_firestore_odm: ^1.0.0-dev.27
  password_strength: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_native_splash:
  # color: "#42a5f5"
  background_image: "assets/logo/splash.png"


flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/illustration/
    - assets/images/
    - assets/dice/
    - assets/pics/
    - lib/images/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/bold_italic.ttf
        - asset: assets/fonts/bold.ttf
          weight: 700
        - asset: assets/fonts/italic.ttf
          style: italic
        - asset: assets/fonts/regular.ttf
    - family: Bungee
      fonts:
        - asset: assets/fonts/bungee/Bungee-Regular.ttf


